language: python

python:
  - "2.7_with_system_site_packages"

before_install:
  - sudo apt-get update
  - sudo apt-get install python-gobject-2

script:
  - eval `dbus-launch --sh-syntax` && cd test && python test_vedbus.py -v
